#!/usr/bin/env python3
"""
builder_smoke.py – Validate a device through the ESPHome Builder install path.

The supported, documented way to install a community device is to paste an
esphome.yaml whose `packages:` block pulls devices/<slug>/packages.yaml from
this repo over git; that package in turn resolves the espcontrol external
component from the pinned upstream tag (espcontrol_component_ref). A real user
(or the ESPHome Builder add-on) then runs `esphome config` / `esphome compile`
over the *resolved* graph.

The per-device compile job in CI does NOT exercise that path: it rewrites
`file:///config` to a local assembly and compiles builds/<slug>.yaml. So a
break in the remote resolution — or a config/pin schema mismatch, e.g. a
config option the pinned component version doesn't accept — stays invisible
until a user hits it in the builder. (See issue #48: a config using
`artwork_image: priority:` against a pre-2.6.0 component fails only on this
path.)

This script reproduces the builder path:

  1. Generate a wrapper config that mirrors the shipped esphome.yaml but pulls
     devices/<slug>/packages.yaml from a chosen git ref of THIS repo.
  2. Run `esphome config` (default) or `esphome compile` (--compile) over it,
     so ESPHome performs the real clone + ref fetch + package graph +
     external-component resolution + schema validation — and, with
     --compile, an actual firmware build against that resolved graph.

`esphome config` alone is validate-only: it catches a resolution or schema
break (see issue #48: a config using `artwork_image: priority:` against a
pre-2.6.0 component fails only on this path) but not a break that only
surfaces once the resolved graph is actually compiled — codegen from a
lambda or template ESPHome doesn't type-check until compile time, or a
component version mismatch `esphome config` doesn't exercise. The per-device
compile job in CI doesn't cover that either: it rewrites `file:///config` to
a local assembly and compiles builds/<slug>.yaml, which is the same content
but reached by an `!include` off the local checkout, never through git
clone + ref fetch the way a real builder resolves it. --compile is the only
mode that does both: real resolution *and* an actual build.

To validate the exact commit under review — not whatever sits on the default
branch — the wrapper points at a local git URL (file://<repo-root>) at the
given ref by default. ESPHome runs the identical resolution it would over
https; only the transport for *this* repo differs, and the upstream component
still resolves remotely at the real pin. Pass --repo-url to test the published
GitHub URL instead (used by the nightly variant).

Usage:
    python3 community/scripts/builder_smoke.py --slug tuya-t3e
    python3 community/scripts/builder_smoke.py --all
    python3 community/scripts/builder_smoke.py --slug tuya-t3e --compile
    python3 community/scripts/builder_smoke.py --slug tuya-t3e \\
        --repo-url https://github.com/lamiskin/espcontrol-community-devices --ref main
    python3 community/scripts/builder_smoke.py --self-test
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DEVICES_JSON = os.path.join(REPO_ROOT, "community", "devices.json")

# Dummy credentials for validation only. The password must be >= 8 chars or
# ESPHome's wifi schema rejects it ("WPA password must be at least 8
# characters long"); it is never used to connect to anything.
SECRETS_YAML = 'wifi_ssid: "ci-smoke"\nwifi_password: "ci-smoke-password"\n'

# ESPHome validates the device name as a hostname: 31 characters max, dropping
# to 24 if a config enables name_add_mac_suffix (it reserves "-AABBCC"). Long
# slugs — seeed-esp32-p4-reterminal-d1001 is 31 on its own — blow that budget,
# so the smoke name is truncated to the stricter limit rather than composed
# blindly from the slug. Shipped configs are unaffected: their substitution is
# a short placeholder the user replaces.
NAME_PREFIX = "ci-"
NAME_MAX_LEN = 24


def load_devices():
    """Return the list of registered device slugs from devices.json."""
    with open(DEVICES_JSON) as f:
        return json.load(f)["devices"]


def smoke_name(slug):
    """Return a hostname-safe device name identifying ``slug``."""
    # Trailing "-" would be an odd hostname, so drop it if truncation lands there.
    return (NAME_PREFIX + slug)[:NAME_MAX_LEN].rstrip("-")


def render_wrapper(slug, repo_url, ref):
    """
    Render a builder-path wrapper config for ``slug``.

    Mirrors the shipped devices/<slug>/esphome.yaml (name/friendly_name, wifi
    from secrets, a remote ``setup`` package), but with the package source
    pinned to ``repo_url`` @ ``ref`` and ``file`` pointing at this device's
    packages.yaml — exactly what a user's esphome.yaml resolves to.
    """
    return (
        "# Auto-generated by community/scripts/builder_smoke.py — do not edit.\n"
        "# Exercises the ESPHome Builder remote-package install path.\n"
        "substitutions:\n"
        f'  name: "{smoke_name(slug)}"\n'
        f'  friendly_name: "CI Smoke {slug}"\n'
        "\n"
        "wifi:\n"
        "  ssid: !secret wifi_ssid\n"
        "  password: !secret wifi_password\n"
        "\n"
        "packages:\n"
        "  setup:\n"
        f"    url: {repo_url}\n"
        f"    ref: {ref}\n"
        f"    file: devices/{slug}/packages.yaml\n"
        "    refresh: 1s\n"
    )


def _default_repo_url(repo_root):
    """Local git URL for the checkout under test (fork-safe, no GitHub RTT)."""
    return "file://" + os.path.abspath(repo_root)


def run_smoke(
    slug, repo_url, ref, esphome_bin="esphome", keep=False, do_compile=False, workdir=None
):
    """
    Run `esphome config` (or, with do_compile=True, `esphome compile`) over
    the builder-path wrapper for ``slug``.

    Returns the esphome exit code (0 = valid/success). Writes the harness to
    a temp dir (or ``workdir``, if given) so ESPHome's .esphome cache and
    generated files never touch the repo.
    """
    pkg_rel = os.path.join("devices", slug, "packages.yaml")
    # Only meaningful for the local (file://) case; a nonexistent package path
    # would otherwise surface as an opaque clone/resolve error.
    if repo_url.startswith("file://"):
        pkg_abs = os.path.join(repo_url[len("file://") :], pkg_rel)
        if not os.path.isfile(pkg_abs):
            print(f"[{slug}] missing {pkg_rel} in {repo_url}", file=sys.stderr)
            return 2

    # A caller doing repeated --compile runs (e.g. nightly, once a day)
    # wants a stable path so PlatformIO/ESPHome's own incremental build
    # cache under it can be persisted across runs by the caller (a fresh
    # tempdir every run defeats that — there's nothing stable to cache).
    # --keep is meaningless together with a caller-supplied --workdir: the
    # caller owns that directory's lifetime either way.
    if workdir:
        os.makedirs(workdir, exist_ok=True)
        keep = True  # caller owns this directory's lifetime, not us
    else:
        workdir = tempfile.mkdtemp(prefix=f"builder-smoke-{slug}-")
    wrapper = os.path.join(workdir, f"{slug}.esphome.yaml")
    with open(os.path.join(workdir, "secrets.yaml"), "w") as f:
        f.write(SECRETS_YAML)
    with open(wrapper, "w") as f:
        f.write(render_wrapper(slug, repo_url, ref))

    command = "compile" if do_compile else "config"
    print(f"[{slug}] esphome {command} via {repo_url}@{ref}", flush=True)
    proc = subprocess.run([esphome_bin, command, wrapper], cwd=workdir)
    if proc.returncode == 0:
        print(f"[{slug}] OK — {'compiled' if do_compile else 'configuration is valid'}")
    else:
        print(f"[{slug}] FAILED — esphome {command} exit {proc.returncode}")
    if not keep:
        # Best-effort cleanup; the temp dir is disposable either way. A
        # caller-supplied --workdir is left alone (its caller may cache it).
        import shutil

        shutil.rmtree(workdir, ignore_errors=True)
    else:
        print(f"[{slug}] harness kept at {workdir}")
    return proc.returncode


def self_test():
    """Validate wrapper rendering without invoking esphome or the network."""
    slugs = load_devices()
    assert slugs, "devices.json has no devices"

    # Every registered device must ship the packages.yaml the wrapper targets.
    for slug in slugs:
        pkg = os.path.join(REPO_ROOT, "devices", slug, "packages.yaml")
        assert os.path.isfile(pkg), f"missing packages.yaml for {slug}"

    # Every registered slug must render a name ESPHome accepts as a hostname,
    # or `esphome config` fails before it ever resolves the package graph.
    for slug in slugs:
        name = smoke_name(slug)
        assert 0 < len(name) <= NAME_MAX_LEN, f"smoke name too long for {slug}: {name}"
        assert re.fullmatch(r"[a-z0-9]([a-z0-9-]*[a-z0-9])?", name), (
            f"smoke name is not hostname-safe for {slug}: {name}"
        )
        assert f'name: "{name}"' in render_wrapper(slug, "file:///tmp/repo", "HEAD")

    # A slug at the length that broke the nightly stays inside the budget.
    assert smoke_name("seeed-esp32-p4-reterminal-d1001") == "ci-seeed-esp32-p4-reterm"
    # Truncation must not leave a trailing hyphen.
    assert smoke_name("aaaaaaaaaaaaaaaaaaaaa-bbb") == "ci-aaaaaaaaaaaaaaaaaaaaa"

    w = render_wrapper("tuya-t3e", "file:///tmp/repo", "HEAD")
    assert "file:///tmp/repo" in w
    assert "ref: HEAD" in w
    assert "file: devices/tuya-t3e/packages.yaml" in w
    assert "!secret wifi_ssid" in w

    # Default URL points at the local checkout (fork-safe / deterministic).
    assert _default_repo_url("/x/y") == "file:///x/y"

    # Password must clear ESPHome's 8-char WPA minimum.
    pw = SECRETS_YAML.split("wifi_password:")[1].strip().strip('"')
    assert len(pw) >= 8, "dummy WPA password too short for esphome schema"

    print("builder_smoke.py self-test: OK")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--slug", help="device slug to validate")
    ap.add_argument("--all", action="store_true", help="validate every device")
    ap.add_argument(
        "--repo-root",
        default=REPO_ROOT,
        help="repo checkout to resolve the package from (default: this repo)",
    )
    ap.add_argument(
        "--repo-url",
        help="explicit git URL for the package source; defaults to file://<repo-root>",
    )
    ap.add_argument("--ref", default="HEAD", help="git ref of the package source")
    ap.add_argument("--esphome-bin", default="esphome", help="esphome executable")
    ap.add_argument("--keep", action="store_true", help="keep the temp harness dir")
    ap.add_argument(
        "--compile",
        action="store_true",
        help="run `esphome compile` instead of `esphome config` — a real "
        "firmware build over the resolved builder-path graph, not just "
        "schema validation",
    )
    ap.add_argument(
        "--workdir",
        help="fixed harness directory instead of a fresh temp dir — lets a "
        "caller persist ESPHome's per-project build cache across repeated "
        "--compile runs (e.g. nightly)",
    )
    ap.add_argument("--self-test", action="store_true", help="run internal self-test")
    args = ap.parse_args()

    if args.self_test:
        sys.exit(self_test())

    repo_url = args.repo_url or _default_repo_url(args.repo_root)

    if args.all:
        slugs = load_devices()
    elif args.slug:
        slugs = [args.slug]
    else:
        ap.error("one of --slug, --all, or --self-test is required")

    failures = []
    for slug in slugs:
        if (
            run_smoke(
                slug,
                repo_url,
                args.ref,
                args.esphome_bin,
                args.keep,
                do_compile=args.compile,
                workdir=args.workdir,
            )
            != 0
        ):
            failures.append(slug)

    if failures:
        print(f"\nbuilder-path validation failed for: {', '.join(failures)}")
        sys.exit(1)
    print(f"\nbuilder-path validation passed for: {', '.join(slugs)}")
    sys.exit(0)


if __name__ == "__main__":
    main()
