#!/usr/bin/env python3
"""
download_stats.py – Aggregate GitHub Release-asset download counts into a
per-device stats page (installs vs OTA, all-time + recent releases).

Firmware binaries are served from GitHub Release assets, so each asset's
download_count is a real per-device, per-version metric:
    <slug>.factory.bin  -> fresh installs (browser installer / factory flash)
    <slug>.ota.bin      -> OTA updates
The manifest.json asset counts are CI-only (consumers read the manifest from
Pages) and are ignored.

The output is a VitePress-ready Markdown page. This is a live artifact: it is
regenerated on every Pages build (see community-pages.yml) and is NOT committed.
Fetch failures are non-fatal — a fallback page is written and the script exits 0
so a GitHub API hiccup can never block the docs/installer deploy.

Usage:
    python3 community/scripts/download_stats.py --output docs/reference/download-stats.md
    python3 community/scripts/download_stats.py --self-test
"""

import argparse
import datetime
import json
import os
import subprocess
import sys

REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)
REPO = "lamiskin/espcontrol-community-devices"
RECENT_N = 5


def load_slugs(repo_root=None):
    root = repo_root or REPO_ROOT
    with open(os.path.join(root, "community", "devices.json"),
              encoding="utf-8") as f:
        return json.load(f).get("devices", [])


def load_names(repo_root=None):
    """slug -> public display name (falls back to slug)."""
    root = repo_root or REPO_ROOT
    path = os.path.join(root, "community", "catalog-fragment.json")
    names = {}
    try:
        with open(path, encoding="utf-8") as f:
            devices = json.load(f).get("devices", {})
        for slug, entry in devices.items():
            name = (entry.get("config", {}).get("public", {}).get("name")
                    or entry.get("public", {}).get("name"))
            if name:
                names[slug] = name
    except (OSError, ValueError):
        pass
    return names


def fetch_releases():
    """
    Return the repo's releases as a list of dicts, or None on any failure
    (caller renders a fallback page — this must never raise).
    """
    try:
        out = subprocess.run(
            ["gh", "api", "--paginate", f"repos/{REPO}/releases?per_page=100"],
            capture_output=True, text=True, timeout=60, check=True,
        ).stdout
        data = json.loads(out)
        return data if isinstance(data, list) else None
    except (subprocess.SubprocessError, OSError, ValueError):
        return None


def _release_time(rel):
    return rel.get("published_at") or rel.get("created_at") or ""


def aggregate(releases, slugs, recent_n=RECENT_N):
    """
    Pure aggregation. Returns:
      {
        'per_device': {slug: {'installs', 'ota', 'total'}},   # all-time
        'recent_tags': [tag, ...],                            # newest first
        'recent': {slug: {tag: total}},                       # per recent rel
        'grand': {'installs', 'ota', 'total'},
      }
    """
    releases = sorted(releases, key=_release_time, reverse=True)

    per_device = {s: {"installs": 0, "ota": 0, "total": 0} for s in slugs}
    recent = {s: {} for s in slugs}
    recent_tags = []

    for i, rel in enumerate(releases):
        tag = rel.get("tag_name", "")
        counts = {a.get("name", ""): a.get("download_count", 0) or 0
                  for a in rel.get("assets", [])}
        is_recent = i < recent_n
        if is_recent:
            recent_tags.append(tag)
        for slug in slugs:
            installs = counts.get(f"{slug}.factory.bin", 0)
            ota = counts.get(f"{slug}.ota.bin", 0)
            per_device[slug]["installs"] += installs
            per_device[slug]["ota"] += ota
            per_device[slug]["total"] += installs + ota
            if is_recent:
                recent[slug][tag] = installs + ota

    grand = {
        "installs": sum(d["installs"] for d in per_device.values()),
        "ota": sum(d["ota"] for d in per_device.values()),
        "total": sum(d["total"] for d in per_device.values()),
    }
    return {"per_device": per_device, "recent_tags": recent_tags,
            "recent": recent, "grand": grand}


def short_tag(tag):
    """community-v0.1.1-upstream.v2.6.3 -> v0.1.1"""
    t = tag[len("community-"):] if tag.startswith("community-") else tag
    return t.split("-upstream")[0].split("+")[0] or tag


HEADER_NOTE = (
    "<!-- GENERATED by community/scripts/download_stats.py — do not edit; "
    "regenerated on every Pages build. -->\n"
)


def render(stats, names, now=None):
    now = now or datetime.datetime.now(datetime.timezone.utc)
    ts = now.strftime("%Y-%m-%d %H:%M UTC")
    per = stats["per_device"]
    # Sort devices by all-time total desc, then name.
    order = sorted(per, key=lambda s: (-per[s]["total"], names.get(s, s)))

    out = [HEADER_NOTE, "# Download stats\n",
           f"_Updated {ts}. Counts come from GitHub Release asset "
           "`download_count`: `factory.bin` = installs, `ota.bin` = OTA "
           "updates. `manifest.json` counts are CI-only and excluded._\n",
           "## All-time per device\n",
           "| Device | Installs | OTA updates | Total |",
           "|---|--:|--:|--:|"]
    for slug in order:
        d = per[slug]
        out.append(f"| {names.get(slug, slug)} | {d['installs']} | "
                   f"{d['ota']} | {d['total']} |")
    g = stats["grand"]
    out.append(f"| **All devices** | **{g['installs']}** | **{g['ota']}** | "
               f"**{g['total']}** |\n")

    tags = stats["recent_tags"]
    if tags:
        cols = " | ".join(short_tag(t) for t in tags)
        out.append(f"## By recent release (last {len(tags)})\n")
        out.append("Total downloads (installs + OTA) per device.\n")
        out.append(f"| Device | {cols} |")
        out.append("|---" + "|--:" * len(tags) + "|")
        for slug in order:
            cells = " | ".join(str(stats["recent"][slug].get(t, 0))
                               for t in tags)
            out.append(f"| {names.get(slug, slug)} | {cells} |")
        out.append("")

    out.append("> A failed OTA that still reached GitHub's download endpoint "
               "can add ~1 to a count, so treat small numbers as approximate.")
    return "\n".join(out) + "\n"


def render_fallback(now=None):
    now = now or datetime.datetime.now(datetime.timezone.utc)
    ts = now.strftime("%Y-%m-%d %H:%M UTC")
    return (HEADER_NOTE + "# Download stats\n\n"
            f"_Stats could not be fetched at {ts}; they will refresh on the "
            "next build._\n")


def generate(output, repo_root=None):
    slugs = load_slugs(repo_root)
    names = load_names(repo_root)
    releases = fetch_releases()
    if releases is None:
        content = render_fallback()
        status = "fallback (fetch failed)"
    else:
        content = render(aggregate(releases, slugs), names)
        status = f"{len(releases)} release(s), {len(slugs)} device(s)"
    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[download_stats] wrote {output} — {status}")
    return 0


def self_test():
    failures = []
    slugs = ["dev-a", "dev-b"]
    names = {"dev-a": "Device A", "dev-b": "Device B"}
    releases = [
        {"tag_name": "community-v0.1.1-upstream.v2.6.3",
         "created_at": "2026-07-22T00:00:00Z", "assets": [
             {"name": "dev-a.factory.bin", "download_count": 2},
             {"name": "dev-a.ota.bin", "download_count": 5},
             {"name": "dev-a-manifest.json", "download_count": 99},
             {"name": "dev-b.ota.bin", "download_count": 1},
         ]},
        {"tag_name": "community-v0.1.0-upstream.v2.6.3",
         "created_at": "2026-07-21T00:00:00Z", "assets": [
             {"name": "dev-a.factory.bin", "download_count": 10},
             {"name": "dev-a.ota.bin", "download_count": 0},
             {"name": "dev-b.factory.bin", "download_count": 3},
         ]},
    ]
    st = aggregate(releases, slugs, recent_n=5)

    # Manifest counts must be excluded; installs/ota summed across releases.
    a = st["per_device"]["dev-a"]
    if a != {"installs": 12, "ota": 5, "total": 17}:
        failures.append(f"dev-a all-time wrong: {a}")
    b = st["per_device"]["dev-b"]
    if b != {"installs": 3, "ota": 1, "total": 4}:
        failures.append(f"dev-b all-time wrong: {b}")
    if st["grand"] != {"installs": 15, "ota": 6, "total": 21}:
        failures.append(f"grand wrong: {st['grand']}")

    # Newest release first.
    if st["recent_tags"][0] != "community-v0.1.1-upstream.v2.6.3":
        failures.append(f"recent order wrong: {st['recent_tags']}")
    # Per-recent-release totals (installs+ota).
    if st["recent"]["dev-a"]["community-v0.1.1-upstream.v2.6.3"] != 7:
        failures.append("dev-a v0.1.1 recent total wrong")
    if st["recent"]["dev-a"]["community-v0.1.0-upstream.v2.6.3"] != 10:
        failures.append("dev-a v0.1.0 recent total wrong")

    if short_tag("community-v0.1.1-upstream.v2.6.3") != "v0.1.1":
        failures.append("short_tag wrong")

    md = render(st, names)
    for needle in ("# Download stats", "Device A", "| **All devices** |",
                   "v0.1.1", "By recent release"):
        if needle not in md:
            failures.append(f"render missing: {needle!r}")
    # A device with more total must sort above one with less.
    if md.index("Device A") > md.index("Device B"):
        failures.append("device ordering (by total) wrong")
    # Manifest CI noise must not appear as a number in the table.
    if "99" in md:
        failures.append("manifest CI count leaked into output")

    # Empty-release case must not raise and must still render a table head.
    empty = aggregate([], slugs)
    if empty["grand"]["total"] != 0 or render(empty, names) is None:
        failures.append("empty releases not handled")

    if "could not be fetched" not in render_fallback():
        failures.append("fallback page wrong")

    if failures:
        for msg in failures:
            print(f"[download_stats] ERROR: self-test: {msg}", file=sys.stderr)
        return 1
    print("[download_stats] self-test passed")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=os.path.join(
        REPO_ROOT, "docs", "reference", "download-stats.md"))
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        sys.exit(self_test())
    sys.exit(generate(args.output))


if __name__ == "__main__":
    main()
