#!/usr/bin/env python3
"""
generate_issue_labels.py – Single source of truth for per-device issue
labels and the bug-report form's device dropdown, both derived from
devices.json + catalog-fragment.json.

Outputs (committed, --check in CI, regenerated when devices change):
    community/device-labels.json          label manifest {slug,name,label}
    .github/ISSUE_TEMPLATE/bug-report.yml  bug form with a device dropdown

The label manifest drives:
    - community-labels.yml       (syncs the labels to GitHub)
    - community-issue-labeler.yml (maps a filed issue's device to its label)

Usage:
    python3 community/scripts/generate_issue_labels.py
    python3 community/scripts/generate_issue_labels.py --check
    python3 community/scripts/generate_issue_labels.py --self-test
"""

import argparse
import difflib
import json
import os
import sys

REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)
LABEL_COLOR = "0052cc"
OTHER_OPTION = "Other / not sure"

GEN_NOTE = ("# GENERATED by community/scripts/generate_issue_labels.py "
            "from devices.json — do not edit by hand.\n")


def load_devices(repo_root=None):
    root = repo_root or REPO_ROOT
    with open(os.path.join(root, "community", "devices.json")) as f:
        slugs = json.load(f)["devices"]
    with open(os.path.join(root, "community",
                           "catalog-fragment.json")) as f:
        catalog = json.load(f)["devices"]
    devices = []
    for slug in slugs:
        name = (catalog.get(slug, {}).get("config", {})
                .get("public", {}).get("name", slug))
        devices.append({"slug": slug, "name": name,
                        "label": f"device:{slug}"})
    return devices


def label_manifest(devices):
    return json.dumps(
        {"color": LABEL_COLOR, "devices": devices}, indent=2) + "\n"


def bug_report_form(devices):
    # Device dropdown options: friendly names + an escape hatch. The
    # labeler maps the selected name back to a slug via the manifest.
    options = "".join(
        f'        - {d["name"]}\n' for d in devices)
    options += f'        - {OTHER_OPTION}\n'
    return (
        GEN_NOTE +
        'name: Bug report (community device)\n'
        'description: Report a problem with a community-supported device.\n'
        'labels: ["bug"]\n'
        'body:\n'
        '  - type: markdown\n'
        '    attributes:\n'
        '      value: |\n'
        '        **This is the community devices repo.** Only report issues\n'
        '        for community-supported devices here — never on the upstream\n'
        '        EspControl repo. For questions about how EspControl itself\n'
        '        works, see the [upstream docs](https://jtenniswood.github.io/espcontrol/).\n'
        '  - type: dropdown\n'
        '    id: device\n'
        '    attributes:\n'
        '      label: Which device?\n'
        '      description: The community device this issue is about.\n'
        '      options:\n'
        + options +
        '    validations:\n'
        '      required: true\n'
        '  - type: input\n'
        '    id: firmware-version\n'
        '    attributes:\n'
        '      label: Firmware version\n'
        '      description: From the panel\'s About page (e.g. v0.0.9-upstream.v2.6.3).\n'
        '    validations:\n'
        '      required: false\n'
        '  - type: textarea\n'
        '    id: what-happened\n'
        '    attributes:\n'
        '      label: What happened?\n'
        '      description: What went wrong, and what you expected instead.\n'
        '    validations:\n'
        '      required: true\n'
        '  - type: textarea\n'
        '    id: steps\n'
        '    attributes:\n'
        '      label: Steps to reproduce\n'
        '    validations:\n'
        '      required: false\n'
        '  - type: checkboxes\n'
        '    id: confirm\n'
        '    attributes:\n'
        '      label: Before submitting\n'
        '      options:\n'
        '        - label: This is a community device, and I am not filing this on the upstream repo.\n'
        '          required: true\n'
        '        - label: I understand community builds may be buggier than officially supported panels.\n'
        '          required: true\n'
    )


def outputs(repo_root=None):
    root = repo_root or REPO_ROOT
    devices = load_devices(root)
    return {
        os.path.join(root, "community", "device-labels.json"):
            label_manifest(devices),
        os.path.join(root, ".github", "ISSUE_TEMPLATE",
                     "bug-report.yml"): bug_report_form(devices),
    }


def emit(check_only=False, repo_root=None):
    stale = False
    for path, content in outputs(repo_root).items():
        rel = os.path.relpath(path, repo_root or REPO_ROOT)
        current = ""
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current == content:
            continue
        if check_only:
            stale = True
            print(f"STALE: {rel}")
            for line in list(difflib.unified_diff(
                    current.splitlines(), content.splitlines(),
                    lineterm=""))[:10]:
                print(f"  {line}")
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"wrote {rel}")
    if check_only:
        if stale:
            print("Issue labels/form stale — run: python3 "
                  "community/scripts/generate_issue_labels.py")
            return 1
        print("Issue labels and bug-report form are current.")
    return 0


def self_test():
    import shutil
    import tempfile
    failures = []
    tmp = tempfile.mkdtemp(prefix="issue_labels_test_")
    try:
        os.makedirs(os.path.join(tmp, "community"))
        os.makedirs(os.path.join(tmp, ".github", "ISSUE_TEMPLATE"))
        with open(os.path.join(tmp, "community", "devices.json"), "w") as f:
            json.dump({"devices": ["dev-a", "dev-b"]}, f)
        with open(os.path.join(tmp, "community",
                               "catalog-fragment.json"), "w") as f:
            json.dump({"devices": {
                "dev-a": {"config": {"public": {"name": "Device A"}}},
                "dev-b": {"config": {"public": {"name": "Device B"}}},
            }}, f)

        devices = load_devices(tmp)
        if [d["label"] for d in devices] != ["device:dev-a",
                                             "device:dev-b"]:
            failures.append("label names wrong")

        form = bug_report_form(devices)
        if "- Device A\n" not in form or "- Device B\n" not in form:
            failures.append("device options missing from form")
        if OTHER_OPTION not in form:
            failures.append("escape-hatch option missing")

        # write + check idempotency
        if emit(repo_root=tmp) != 0:
            failures.append("emit failed")
        if emit(check_only=True, repo_root=tmp) != 0:
            failures.append("check not idempotent after write")

        # drift is caught
        with open(os.path.join(tmp, "community", "devices.json"), "w") as f:
            json.dump({"devices": ["dev-a"]}, f)
        if emit(check_only=True, repo_root=tmp) == 0:
            failures.append("check did not catch device removal drift")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if failures:
        for m in failures:
            print(f"[generate_issue_labels] self-test FAIL: {m}",
                  file=sys.stderr)
        return 1
    print("[generate_issue_labels] self-test passed")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        sys.exit(self_test())
    sys.exit(emit(check_only=args.check))


if __name__ == "__main__":
    main()
