#!/usr/bin/env python3
"""
generate_docs.py – Generate the per-device docs pages, the home-page device
table, and the sidebar entries from catalog-fragment.json + STATUS.md.

Outputs (committed, and regenerated in the pages workflow):
    docs/screens/<slug>.md          one page per device in devices.json
    docs/parts/device-table.md      device table included by docs/index.md
    docs/.vitepress/device-sidebar.json  sidebar items for config.mts

Page structure mirrors upstream EspControl's per-screen docs so users move
between the two sites without relearning navigation.

Usage:
    python3 community/scripts/generate_docs.py
    python3 community/scripts/generate_docs.py --check   # fail if stale
"""

import argparse
import difflib
import json
import os
import re
import sys

REPO_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)
DOCS = os.path.join(REPO_ROOT, "docs")

CHIP_NAMES = {"esp32-s3": "ESP32-S3", "esp32-p4": "ESP32-P4"}

HEADER = """<!-- =============================================================================
GENERATED — do not edit by hand.
Generated by community/scripts/generate_docs.py from
community/catalog-fragment.json and community/STATUS.md.
============================================================================= -->
"""

STATUS_SECTIONS = {
    "Working": (
        "tip",
        "Hardware-verified",
        "This device has been verified on real hardware — it compiles, "
        "flashes, and runs EspControl correctly.",
    ),
    "Untested": (
        "warning",
        "Not yet hardware-verified",
        "This device compiles and is flashable, but nobody has confirmed it "
        "on real hardware yet. It may not work. If you own this panel, "
        "[verifying it](/reference/support-policy#hardware-verification) "
        "is the most valuable contribution you can make.",
    ),
    "Broken": (
        "danger",
        "Currently broken",
        "This device does not compile against the current pinned upstream "
        "version and has been pulled from the installer. Already-flashed "
        "panels keep working but will not receive updates until it is fixed.",
    ),
}


def parse_status(path):
    rows = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            parts = [p.strip() for p in line.split("|")]
            if len(parts) >= 7 and parts[2] and parts[2] != "Slug" \
                    and not set(parts[2]) <= {"-"}:
                rows[parts[2]] = {
                    "name": parts[1],
                    "status": parts[3],
                    "verified": parts[4],
                    "owner": parts[5],
                    "source": parts[6],
                }
    return rows


def size_sort_key(entry):
    match = re.match(r"([\d.]+)", entry["size"])
    return -float(match.group(1)) if match else 0.0


def load_devices():
    with open(os.path.join(REPO_ROOT, "community", "devices.json")) as f:
        slugs = json.load(f)["devices"]
    with open(os.path.join(REPO_ROOT, "community",
                           "catalog-fragment.json")) as f:
        catalog = json.load(f)["devices"]
    status = parse_status(
        os.path.join(REPO_ROOT, "community", "STATUS.md"))

    devices = []
    for slug in slugs:
        entry = catalog.get(slug)
        if entry is None:
            print(f"ERROR: {slug} missing from catalog-fragment.json",
                  file=sys.stderr)
            sys.exit(1)
        row = status.get(slug, {})
        config = entry.get("config", {})
        public = config.get("public", {})
        layout = config.get("layout", {})
        devices.append({
            "slug": slug,
            "name": public.get("name", slug),
            "size": public.get("screenSize", "?"),
            "resolution": public.get("resolution", "?"),
            "orientation": public.get("orientation", "?"),
            "slots": config.get("slots", "?"),
            "grid": f"{layout.get('cols', '?')} × {layout.get('rows', '?')}",
            "chip": CHIP_NAMES.get(
                entry.get("profiles", {}).get("platform", ""), "?"),
            "status": row.get("status", "Untested"),
            "owner": row.get("owner", ""),
            "source": row.get("source", ""),
            "buy": public.get("buy", ""),
            "case": public.get("case", ""),
        })
    devices.sort(key=size_sort_key)
    return devices


def short_size(size):
    match = re.match(r"([\d.]+)", size)
    return f"{match.group(1)}-inch" if match else size


def device_page(d):
    section_kind, section_title, section_body = STATUS_SECTIONS.get(
        d["status"], STATUS_SECTIONS["Untested"])

    install = ""
    if d["status"] in ("Working", "Untested"):
        install = f"""## Install

Connect the display to your computer with a **USB-C data cable**, then click
the button below (Chrome or Edge on desktop).

<EspInstallButton slug="{d['slug']}" />

For WiFi setup and Home Assistant pairing the flow is identical to official
EspControl — follow the [Install guide](/getting-started/install).
"""
    else:
        install = """## Install

Installation is unavailable while this device is not building — see the
status note above.
"""

    credit = ""
    if d["source"]:
        credit = (f"\nCommunity port contributed via {d['source']}"
                  + (f" by {d['owner']}" if d["owner"] else "") + ".\n")

    buy = ""
    if d["buy"]:
        buy = f"""## Where to buy

Available on [AliExpress]({d['buy']}).

"""

    case = ""
    if d["case"]:
        case = f"""## 3D printed case

A community-made 3D-printable case is available on
[Thingiverse]({d['case']}).

"""

    return f"""---
title: {short_size(d['size'])} {d['name']}
description: "Community EspControl build for the {d['name']} — {d['size']} {d['resolution']} {d['orientation'].lower()} touchscreen with {d['slots']} cards, powered by {d['chip']}."
---
{HEADER}
<!--@include: ../parts/warning.md-->

# {short_size(d['size'])} {d['name']}

The **{d['name']}** is a {short_size(d['size'])} {d['orientation'].lower()}
touchscreen powered by **{d['chip']}**, with room for **{d['slots']} cards**
on the home screen.
{credit}
::: {section_kind} {section_title}
{section_body}
:::

## Specifications

| | |
|---|---|
| **Screen size** | {d['size']} |
| **Resolution** | {d['resolution']} |
| **Orientation** | {d['orientation']} |
| **Processor** | {d['chip']} |
| **Card grid** | {d['grid']} ({d['slots']} cards) |

{buy}{case}{install}
## ESPHome Manual Setup

If you use ESPHome and prefer to compile firmware yourself:

```yaml
substitutions:
  name: "your-device-name"
  friendly_name: "Your Device Name"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  setup:
    url: https://github.com/lamiskin/espcontrol-community-devices/
    file: devices/{d['slug']}/packages.yaml
    refresh: 1s
```

## Configuration and Features

Everything about using and configuring EspControl — cards, subpages, display
behaviour, Home Assistant setup — is identical to official devices and
documented upstream: [EspControl docs](https://jtenniswood.github.io/espcontrol/).
Device-specific problems belong on the
[community issue tracker](https://github.com/lamiskin/espcontrol-community-devices/issues)
— see the [Support Policy](/reference/support-policy).
"""


def device_table(devices):
    lines = [HEADER,
             "| Device | Size | Resolution | Cards | Processor | Status |",
             "|---|---|---|---|---|---|"]
    # Ordered by device name (the sidebar keeps the by-size ordering).
    for d in sorted(devices, key=lambda d: d["name"].lower()):
        lines.append(
            f"| [{d['name']}](/screens/{d['slug']}) | {d['size']} | "
            f"{d['resolution']} | {d['slots']} | {d['chip']} | "
            f"{d['status']} |")
    return "\n".join(lines) + "\n"


def sidebar(devices):
    # Use the same device name as the Supported Devices table (no size prefix).
    return [
        {"text": d["name"], "link": f"/screens/{d['slug']}"}
        for d in devices
    ]


def emit(check_only=False):
    devices = load_devices()
    outputs = {}
    for d in devices:
        outputs[os.path.join(DOCS, "screens", f"{d['slug']}.md")] = \
            device_page(d)
    outputs[os.path.join(DOCS, "parts", "device-table.md")] = \
        device_table(devices)
    outputs[os.path.join(DOCS, ".vitepress", "device-sidebar.json")] = \
        json.dumps(sidebar(devices), indent=2) + "\n"

    # Stale committed pages for devices no longer registered
    screens_dir = os.path.join(DOCS, "screens")
    if os.path.isdir(screens_dir):
        known = {os.path.join(screens_dir, f"{d['slug']}.md")
                 for d in devices}
        for name in os.listdir(screens_dir):
            path = os.path.join(screens_dir, name)
            if name.endswith(".md") and path not in known:
                if check_only:
                    print(f"STALE: {path} (device no longer registered)")
                    return 1
                os.remove(path)
                print(f"removed stale {os.path.relpath(path, REPO_ROOT)}")

    stale = False
    for path, content in outputs.items():
        rel = os.path.relpath(path, REPO_ROOT)
        current = ""
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current == content:
            continue
        if check_only:
            stale = True
            print(f"STALE: {rel}")
            for line in list(difflib.unified_diff(
                    current.splitlines(), content.splitlines(),
                    lineterm=""))[:12]:
                print(f"  {line}")
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"wrote {rel}")

    if check_only:
        if stale:
            print("Docs are stale — run: python3 "
                  "community/scripts/generate_docs.py")
            return 1
        print(f"Docs are current ({len(outputs)} generated files).")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if generated docs are stale")
    args = parser.parse_args()
    sys.exit(emit(check_only=args.check))


if __name__ == "__main__":
    main()
